---
- name: Playbook docker image
  hosts: localhost
  gather_facts: false
  tasks:
    - name: stop container
      docker_container:
        name: ecommerce
        state: stopped
      ignore_errors: true
    - name: Remove container
      docker_container:
        name: ecommerce
        state: absent
      ignore_errors: true
    - name: Remove image
      docker_image:
        name: bookstore
        tag: v3.0
        state: absent
      ignore_errors: true
    - name: Build an image and push it to docker hub
      docker_image:
        build:
          path: ./
        name: bookstore
        tag: latest
        force_tag: true
        repository: sami4rhimi/bookstore:latest
        push: true
        source: build
    - name: Pull the Docker image from the registry
      docker_image:
        name: bookstore
        tag: latest
        force_tag: true
        source: pull
    - name: Run a Docker container with environment variables
      docker_container:
        name: ecommerce
        image: sami4rhimi/bookstore:latest
        state: started
        ports:
          - "5000:5000"
        env:
          MONGO_USER: "{{ lookup('env', 'MONGO_USER') }}"
          MONGO_PASS: "{{ lookup('env', 'MONGO_PASS') }}"
          SECRET_KEY: "{{ lookup('env', 'SECRET_KEY') }}"
        healthcheck:
          test: ["CMD", "curl", "--fail", "http://localhost:5000"]
          interval: 10s
          timeout: 5s
          retries: 3
          start_period: 30s
          start_interval: 10s
    - name: get running containers
      shell: docker ps
      register: list
    - name: list running containers
      debug:
        var: list.stdout
